pipeline {
    agent any

    tools {
        python 'Python3'  // Make sure "Python3" is defined in Global Tools config
    }

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/alx-backend-python/alx-backend-python.git',
                    credentialsId: 'your-github-credentials-id'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                    cd messaging_app
                    python3 -m venv ${VENV_DIR}
                    source ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd messaging_app
                    source ${VENV_DIR}/bin/activate
                    pytest --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            steps {
                junit 'messaging_app/report.xml'
            }
        }
    }

    triggers {
        // Manual trigger only
    }
}
